/*
 * File: app/view/XMLParserViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XMLParser.view.XMLParserViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.xmlparserviewport',

    requires: [
        'XMLParser.view.XMLParserViewportViewModel',
        'XMLParser.view.XMLParserViewportViewController',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.toolbar.Toolbar',
        'Ext.selection.RowModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.chart.PolarChart',
        'Ext.chart.series.Pie3D',
        'Ext.chart.interactions.Rotate',
        'Ext.chart.legend.Legend',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category3D',
        'Ext.chart.axis.Numeric3D',
        'Ext.chart.series.Bar3D'
    ],

    controller: 'xmlparserviewport',
    viewModel: {
        type: 'xmlparserviewport'
    },
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'treepanel',
            region: 'center',
            itemId: 'xmlTreePanel',
            title: 'Query Items',
            store: 'MyTreeStore',
            displayField: 'description',
            rootVisible: false,
            viewConfig: {
                width: 51
            },
            listeners: {
                checkchange: 'onTreepanelCheckChange'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Check All',
                            listeners: {
                                click: 'onCheckAllClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Uncheck All',
                            listeners: {
                                click: 'onUncheckAllButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'Export',
                            text: 'Download Result',
                            listeners: {
                                click: 'onExportClick'
                            }
                        }
                    ]
                }
            ],
            selModel: {
                selType: 'rowmodel'
            }
        },
        {
            xtype: 'tabpanel',
            region: 'east',
            split: true,
            itemId: 'tabPanel',
            width: '80%',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'ExtJS Charts',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'polar',
                                    reference: 'pie1',
                                    flex: 1,
                                    height: 300,
                                    itemId: 'pie1',
                                    width: 400,
                                    captions: {
                                        title: '% Cases By Sex'
                                    },
                                    colors: [
                                        '#115fa6',
                                        '#94ae0a',
                                        '#a61120',
                                        '#ff8809',
                                        '#ffd13e',
                                        '#a61187',
                                        '#24ad9a',
                                        '#7c7474',
                                        '#a66111'
                                    ],
                                    store: 'sex',
                                    innerPadding: 20,
                                    series: [
                                        {
                                            type: 'pie3d',
                                            highlight: true,
                                            label: {
                                                display: 'none',
                                                field: 'translation'
                                            },
                                            tooltip: {
                                                trackMouse: true,
                                                renderer: function(tooltip, record, item){
                                            
                                            
                                            var total = 0;
                                            
                                            record.store.each(function(rec){
                                                total += rec.get("value");
                                            });
                                            
                                            
                                            tooltip.setHtml(record.get('translation') + ': ' + Math.round(record.get('value')/ total * 100) + '%');
                                            }
                                            },
                                            angleField: 'value'
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'rotate'
                                        }
                                    ],
                                    legend: {
                                        xtype: 'legend'
                                    }
                                },
                                {
                                    xtype: 'polar',
                                    reference: 'pie3',
                                    flex: 1,
                                    height: 300,
                                    itemId: 'pie3',
                                    width: 400,
                                    captions: {
                                        title: '% Cases By Vital Status'
                                    },
                                    colors: [
                                        '#115fa6',
                                        '#94ae0a',
                                        '#a61120',
                                        '#ff8809',
                                        '#ffd13e',
                                        '#a61187',
                                        '#24ad9a',
                                        '#7c7474',
                                        '#a66111'
                                    ],
                                    store: 'vitalStatus',
                                    innerPadding: 20,
                                    series: [
                                        {
                                            type: 'pie3d',
                                            highlight: true,
                                            label: {
                                                display: 'none',
                                                field: 'translation'
                                            },
                                            tooltip: {
                                                trackMouse: true,
                                                renderer: function(tooltip, record, item){
                                            
                                            
                                            var total = 0;
                                            
                                            record.store.each(function(rec){
                                                total += rec.get("value");
                                            });
                                            
                                            
                                            tooltip.setHtml(record.get('translation') + ': ' + Math.round(record.get('value')/ total * 100) + '%');
                                            }
                                            },
                                            angleField: 'value'
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'rotate'
                                        }
                                    ],
                                    legend: {
                                        xtype: 'legend'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'cartesian',
                                    reference: 'col1',
                                    flex: 1,
                                    height: 250,
                                    itemId: 'col1',
                                    width: 400,
                                    captions: {
                                        title: '# of Cases By Race'
                                    },
                                    insetPadding: 20,
                                    store: 'race1',
                                    axes: [
                                        {
                                            type: 'category3d',
                                            renderer: function(axis, label, layoutContext, lastLabel) {

                                                label = label.split(" - ")[0];
                                                return label;
                                            },
                                            fields: [
                                                'translation'
                                            ],
                                            position: 'bottom',
                                            title: 'Race'
                                        },
                                        {
                                            type: 'numeric3d',
                                            fields: [
                                                'value'
                                            ],
                                            grid: {
                                                odd: {
                                                    fillStyle: 'rgba(245, 245, 245, 1.0)'
                                                },
                                                even: {
                                                    fillStyle: 'rgba(255, 255, 255, 1.0)'
                                                }
                                            },
                                            position: 'left'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'bar3d',
                                            highlight: true,
                                            label: {
                                                field: 'value',
                                                display: 'insideEnd'
                                            },
                                            tooltip: {
                                                trackMouse: true,
                                                renderer: function(tooltip, record, item){
                                            
                                             var formatString = '0,000 (millions of USD)';
                                            
                                            var trans = record.get("translation").split(" - ");
                                            
                                            tooltip.setHtml(trans[1] + ": "+record.get("value"));
                                            }
                                            },
                                            xField: 'translation',
                                            yField: [
                                                'value'
                                            ],
                                            fullStackTotal: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'polar',
                                    reference: 'pie2',
                                    flex: 1,
                                    height: 300,
                                    itemId: 'pie2',
                                    width: 400,
                                    captions: {
                                        title: '% Cases By Age Range'
                                    },
                                    colors: [
                                        '#115fa6',
                                        '#94ae0a',
                                        '#a61120',
                                        '#ff8809',
                                        '#ffd13e',
                                        '#a61187',
                                        '#24ad9a',
                                        '#7c7474',
                                        '#a66111'
                                    ],
                                    store: 'ageAtDiagnosis',
                                    innerPadding: 20,
                                    series: [
                                        {
                                            type: 'pie3d',
                                            highlight: true,
                                            label: {
                                                display: 'none',
                                                field: 'translation'
                                            },
                                            tooltip: {
                                                trackMouse: true,
                                                renderer: function(tooltip, record, item){
                                            
                                            
                                            var total = 0;
                                            
                                            record.store.each(function(rec){
                                                total += rec.get("value");
                                            });
                                            
                                            
                                            tooltip.setHtml(record.get('translation') + ': ' + Math.round(record.get('value')/ total * 100) + '%');
                                            }
                                            },
                                            angleField: 'value'
                                        }
                                    ],
                                    interactions: [
                                        {
                                            type: 'rotate'
                                        }
                                    ],
                                    legend: {
                                        xtype: 'legend'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'chart7',
                    layout: 'fit',
                    title: 'By Site',
                    items: [
                        {
                            xtype: 'cartesian',
                            reference: 'col2',
                            flex: 1,
                            height: 250,
                            itemId: 'col2',
                            width: 400,
                            captions: {
                                title: '# of Cases By Site'
                            },
                            insetPadding: 20,
                            store: 'primarySite',
                            axes: [
                                {
                                    type: 'category3d',
                                    renderer: function(axis, label, layoutContext, lastLabel) {

                                        label = label.split(" - ")[0];
                                        return label;
                                    },
                                    fields: [
                                        'translation'
                                    ],
                                    position: 'bottom',
                                    title: 'Site'
                                },
                                {
                                    type: 'numeric3d',
                                    fields: [
                                        'value'
                                    ],
                                    grid: {
                                        odd: {
                                            fillStyle: 'rgba(245, 245, 245, 1.0)'
                                        },
                                        even: {
                                            fillStyle: 'rgba(255, 255, 255, 1.0)'
                                        }
                                    },
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'bar3d',
                                    highlight: true,
                                    label: {
                                        field: 'value',
                                        display: 'insideEnd'
                                    },
                                    tooltip: {
                                        trackMouse: true,
                                        renderer: function(tooltip, record, item){
                                    
                                     var formatString = '0,000 (millions of USD)';
                                    
                                    var trans = record.get("translation").split(" - ");
                                    
                                    tooltip.setHtml(trans[1] + ": "+record.get("value"));
                                    }
                                    },
                                    xField: 'translation',
                                    yField: [
                                        'value'
                                    ],
                                    fullStackTotal: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'chart1',
                    layout: 'fit',
                    title: 'KM Chart',
                    items: [
                        {
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                src: 'http://52.90.197.198/d3graphs/trialKM.html'
                            },
                            itemId: 'chart1Comp',
                            listeners: {
                                afterrender: 'onChart1CompAfterRender'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'chart2',
                    itemId: 'chart2',
                    layout: 'fit',
                    title: 'US Map',
                    items: [
                        {
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                src: 'http://52.90.197.198/d3graphs/USMap.html'
                            },
                            itemId: 'chart2Comp',
                            listeners: {
                                afterrender: 'onChart2CompAfterRender'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 535,
                    itemId: 'chart3',
                    layout: 'fit',
                    title: 'County Map',
                    tabConfig: {
                        xtype: 'tab',
                        hidden: true
                    },
                    items: [
                        {
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                src: 'http://52.90.197.198/d3graphs/choropleth.html'
                            },
                            itemId: 'chart3Comp'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    hidden: true,
                    itemId: 'chart4',
                    layout: 'fit',
                    title: 'Pie Chart',
                    items: [
                        {
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                src: 'http://52.90.197.198/d3graphs/Pie.html'
                            },
                            itemId: 'chart4Comp'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    hidden: true,
                    itemId: 'chart6',
                    layout: 'fit',
                    title: 'Pie Chart',
                    items: [
                        {
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                src: 'http://52.90.197.198/d3graphs/Bar.html'
                            },
                            itemId: 'chart6Comp'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'chart5',
                    layout: 'fit',
                    title: 'By County',
                    items: [
                        {
                            xtype: 'component',
                            autoEl: {
                                tag: 'iframe',
                                src: 'http://52.90.197.198/d3graphs/choroplethAll.html'
                            },
                            itemId: 'chart5Comp',
                            listeners: {
                                afterrender: 'onChart5CompAfterRender'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        boxready: 'onViewportBoxReady'
    }

});