/*
 * File: app/store/MyTreeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('XMLParser.store.MyTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'Ext.data.field.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyTreeStore',
            root: {
                expanded: true,
                rootVisible: false,
                children: [
                    {
                        description: 'Sex',
                        naaccrId: 'sex',
                        iconCls: 'x-tree-noicon',
                        comparator: 'IN',
                        expanded: true,
                        children: [
                            {
                                description: 'Male',
                                naaccrId: 'sex',
                                value: '1',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            },
                            {
                                description: 'Female',
                                naaccrId: 'sex',
                                value: '2',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            }
                        ]
                    },
                    {
                        description: 'Age at Diagnosis',
                        naaccrId: 'ageAtDiagnosis',
                        iconCls: 'x-tree-noicon',
                        comparator: 'RANGE',
                        operand: 'OR',
                        expanded: true,
                        children: [
                            {
                                description: 'Under 18',
                                naaccrId: 'ageAtDiagnosis',
                                comparator: '$lt',
                                value: 18,
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            },
                            {
                                description: '18-65',
                                naaccrId: 'ageAtDiagnosis',
                                start: 18,
                                comparator: 'RANGE',
                                end: 65,
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            },
                            {
                                description: 'Over 65',
                                naaccrId: 'ageAtDiagnosis',
                                comparator: '$gte',
                                value: 65,
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            }
                        ]
                    },
                    {
                        description: 'Vital Status',
                        naaccrId: 'vitalStatus',
                        iconCls: 'x-tree-noicon',
                        comparator: 'IN',
                        expanded: true,
                        children: [
                            {
                                description: 'Dead',
                                naaccrId: 'vitalStatus',
                                value: 0,
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            },
                            {
                                description: 'Alive',
                                naaccrId: 'vitalStatus',
                                value: 1,
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                leaf: true
                            }
                        ]
                    },
                    {
                        description: 'Race',
                        naaccrId: 'race1',
                        iconCls: 'x-tree-noicon',
                        comparator: 'IN',
                        expanded: true,
                        children: [
                            {
                                naaccrId: 'race1',
                                value: '01',
                                description: '01 - White',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '02',
                                description: '02 - Black',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '03',
                                description: '03 - American Indian, Aleutian, Eskimo',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '04',
                                description: '04 - Chinese',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '05',
                                description: '05 - Japanese',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '05',
                                description: '06 - Filipino',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '05',
                                description: '07 - Hawaiian',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: '05',
                                description: '08 - Korean',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 10,
                                description: '10 - Vietnamese',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 11,
                                description: '11 - Laotian',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 12,
                                description: '12 - Hmong',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 13,
                                description: '13 - Kampuchean (Cambodian)',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 14,
                                description: '14 - Thai',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 15,
                                description: '15 - Asian Indian or Pakistani, NOS (formerly 09)',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 16,
                                description: '16 - Asian Indian',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 17,
                                description: '17 - Pakistani',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 21,
                                description: '21 - Chamorran',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 22,
                                description: '22 - Guamanian, NOS',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 25,
                                description: '25 - Polynesian, NOS',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 26,
                                description: '26 - Tahitian',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 27,
                                description: '27 - Samoan',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 28,
                                description: '28 - Tongan',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 30,
                                description: '30 - Melanesian, NOS',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 31,
                                description: '31 - Fiji Islander',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 96,
                                description: '96 - Other Asian including Asian, NOS and Oriental, NOS',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 98,
                                description: '98 - Other',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            },
                            {
                                naaccrId: 'race1',
                                value: 99,
                                description: '99 - Unknown',
                                leaf: true,
                                checked: true,
                                iconCls: 'x-tree-noicon'
                            }
                        ]
                    },
                    {
                        description: 'Primary Site',
                        naaccrId: 'primarySite',
                        iconCls: 'x-tree-noicon',
                        expanded: true,
                        comparator: 'IN',
                        children: [
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C00 - LIP',
                                leaf: true,
                                value: 'C00'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C01 - TONGUE',
                                leaf: true,
                                value: 'C01'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C02 - OTHER AND UNSPECIFIED PARTS OF TONGUE',
                                leaf: true,
                                value: 'C02'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C03 - GUM',
                                leaf: true,
                                value: 'C03'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C04 - FLOOR OF MOUTH',
                                leaf: true,
                                value: 'C04'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C05 - PALATE',
                                leaf: true,
                                value: 'C05'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C06 - OTHER AND UNSPECIFIED PARTS OF MOUTH',
                                leaf: true,
                                value: 'C06'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C07 - PAROTID GLAND',
                                leaf: true,
                                value: 'C07'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C08 - OTHER AND UNSPECIFIED MAJOR SALIVARY GLANDS',
                                leaf: true,
                                value: 'C08'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C09 - TONSIL',
                                leaf: true,
                                value: 'C09'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C10 - OROPHARNYX',
                                leaf: true,
                                value: 'C10'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C11 - NASOPHARYNX',
                                leaf: true,
                                value: 'C11'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C12 - PYRIFORM SINUS',
                                leaf: true,
                                value: 'C12'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C13 - HYPOPHARYNX',
                                leaf: true,
                                value: 'C13'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C14 - OTHER AND ILL-DEFINED SITES IN LIP, ORAL CAVITY AND PHARYNX',
                                leaf: true,
                                value: 'C14'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C15 - ESOPHAGUS',
                                leaf: true,
                                value: 'C15'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C16 - STOMACH',
                                leaf: true,
                                value: 'C16'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C17 - SMALL INTESTINE',
                                leaf: true,
                                value: 'C17'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C18 - COLON',
                                leaf: true,
                                value: 'C18'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C19 - RECTOSIGMOID JUNCTION',
                                leaf: true,
                                value: 'C19'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C20 - RECTUM',
                                leaf: true,
                                value: 'C20'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C21 - ANAL CANAL & ANUS',
                                leaf: true,
                                value: 'C21'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C22 - LIVER, INTRAHEPATIC BILE DUCTS',
                                leaf: true,
                                value: 'C22'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C23 - GALLBLADDER',
                                leaf: true,
                                value: 'C23'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C24 - OTHER AND UNSPECIFIED PARTS OF BILIARY TRACT',
                                leaf: true,
                                value: 'C24'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C25 - PANCREAS',
                                leaf: true,
                                value: 'C25'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C26 - OTHER AND ILL-DEFINED DIGESTIVE ORGANS',
                                leaf: true,
                                value: 'C26'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C30 - NASAL CAVITY AND  MIDDLE EAR',
                                leaf: true,
                                value: 'C30'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C31 - ACCESSORY SINUSES',
                                leaf: true,
                                value: 'C31'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C32 - LARYNX',
                                leaf: true,
                                value: 'C32'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C33 - TRACHEA',
                                leaf: true,
                                value: 'C33'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C34 - LUNG & BRONCHUS',
                                leaf: true,
                                value: 'C34'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C37 - THYMUS',
                                leaf: true,
                                value: 'C37'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C38 - HEART, MEDIASTINUM, AND PLEURA',
                                leaf: true,
                                value: 'C38'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C39 - OTHER AND ILL-DEFINED SITES WITHIN RESPIRATORY SYSTEM AND INTRATHORACIC ORGANS',
                                leaf: true,
                                value: 'C39'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C40 - BONES, JOINTS AND ARTICULAR CARTILAGE OF LIMBS',
                                leaf: true,
                                value: 'C40'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C41 - BONES, JOINTS AND ARTICULAR CARTILAGE OF OTHER AND UNSPECIFIED SITES',
                                leaf: true,
                                value: 'C41'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C42 - HEMATOPOIETIC AND RETICULOENDOTHELIAL SYSTEMS',
                                leaf: true,
                                value: 'C42'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C44 - SKIN',
                                leaf: true,
                                value: 'C44'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C47 - PERIPHERAL NERVES AND AUTONOMIC NERVOUS SYSTEM',
                                leaf: true,
                                value: 'C47'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C48 - RETROPERITONEUM & PERITONEUM',
                                leaf: true,
                                value: 'C48'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C49 - CONNECTIVE, SUBCUTANEOUS AND OTHER SOFT TISSUES',
                                leaf: true,
                                value: 'C49'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C50 - BREAST',
                                leaf: true,
                                value: 'C50'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C51 - VULVA',
                                leaf: true,
                                value: 'C51'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C52 - VAGINA',
                                leaf: true,
                                value: 'C52'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C53 - CERVIX UTERI',
                                leaf: true,
                                value: 'C53'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C54 - CORPUS UTERI',
                                leaf: true,
                                value: 'C54'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C55 - UTERUS, NOS',
                                leaf: true,
                                value: 'C55'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C56 - OVARY',
                                leaf: true,
                                value: 'C56'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C57 - OTHER AND UNSPECIFIED FEMALE GENITAL ORGANS',
                                leaf: true,
                                value: 'C57'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C58 - PLACENTA',
                                leaf: true,
                                value: 'C58'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C60 - PENIS',
                                leaf: true,
                                value: 'C60'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C61 - PROSTATE GLAND',
                                leaf: true,
                                value: 'C61'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C62 - TESTIS',
                                leaf: true,
                                value: 'C62'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C63 - OTHER AND UNSPECIFIED MALE GENITAL ORGANS',
                                leaf: true,
                                value: 'C63'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C64 - KIDNEY',
                                leaf: true,
                                value: 'C64'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C65 - RENAL PELVIS',
                                leaf: true,
                                value: 'C65'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C66 - URETER',
                                leaf: true,
                                value: 'C66'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C67 - BLADDER',
                                leaf: true,
                                value: 'C67'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C68 - OTHER AND UNSPECIFIED URINARY ORGANS',
                                leaf: true,
                                value: 'C68'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C69 - EYE AND ADNEXA',
                                leaf: true,
                                value: 'C69'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C70 - MENINGES',
                                leaf: true,
                                value: 'C70'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C71 - BRAIN',
                                leaf: true,
                                value: 'C71'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C72 - SPINAL CORD, CRANIAL NERVES, AND OTHER PARTS OF CENTRAL NERVOUS SYSTEM',
                                leaf: true,
                                value: 'C72'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C73 - THYROID GLAND',
                                leaf: true,
                                value: 'C73'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C74 - ADRENAL GLANDS',
                                leaf: true,
                                value: 'C74'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C75 - OTHER ENDOCRINE GLANDS AND RELATED STRUCTURES',
                                leaf: true,
                                value: 'C75'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C76 - OTHER AND ILL-DEFINED SITES',
                                leaf: true,
                                value: 'C76'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C77 - LYMPH NODES',
                                leaf: true,
                                value: 'C77'
                            },
                            {
                                naaccrId: 'primarySite',
                                iconCls: 'x-tree-noicon',
                                checked: true,
                                description: 'C80 - UNKNOWN',
                                leaf: true,
                                value: 'C80'
                            }
                        ]
                    }
                ]
            },
            fields: [
                {
                    name: 'TxLabel'
                },
                {
                    name: 'TxType'
                },
                {
                    name: 'description'
                },
                {
                    name: 'sqlColumn'
                }
            ]
        }, cfg)]);
    }
});